name: pr_jsonlint

on:
  pull_request:
    paths:
      - 'module/webroot/locales/*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JSON linter
        run: npm install -g jsonlint

      - name: Lint JSON files
        run: |
          for file in $(find module/webroot/locales -name "*.json"); do
            echo "Checking $file"
            if ! jsonlint "$file"; then
              echo "Error in $file"
              exit 1
            fi
          done